apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rdma-2-dhcp
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "type": "host-device",
      "pciBusID": "0000:98:00.0",
      "ipam": {
          "type": "dhcp",
          "request": [
            { 
              "option": "121" 
            }
          ]
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rdma-2-static-via
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "static-route-network",
      "type": "host-device",
      "pciBusID": "0000:98:00.0",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.144.60/32"
          }
        ],
        "routes": [
          {
            "dst": "192.168.144.1/32",
            "gw": "0.0.0.0"
          },
          {
            "dst": "192.168.144.0/21",
            "gw": "192.168.144.1"
          }
        ]
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rdma-2-static
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "type": "host-device",
      "pciBusID": "0000:98:00.0",
      "ipam": {
        "type":"static",
        "addresses": [
          {
            "address": "192.168.144.52/21",
            "gateway": "192.168.144.1"
          }
        ]
        }
    }

