apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rdma-2-dhcp
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "type": "host-device",
      "pciBusID": "0000:98:00.0",
      "ipam": {
          "type": "dhcp",
          "request": [
            { 
              "option": "121" 
            }
          ]
      }
    }

